### ISSUE TITLE
Created Derivative Work, Full rewrite needed.

### ISSUE THREAD

**Issue by alycecil** [inexcode/HumanlikeLifeStages#16] opened 2018-12-08 20:24 UTC

**Comment by inexcode** [comment] 2018-12-08 20:32
Duplicate of #2

**Closed as completed** 2018-12-08 20:32 UTC
Labels: duplicate, wontfix

**Comment by inexcode** [comment] 2018-12-08 21:24
@alycecil just so you know, I'm willing to DM you and have a friendly talk about this situation. You can accept my friend invitation on Steam or send me your contact details here.

**Comment by EPSIL0N** [comment] 2018-12-09 06:45
I've received similar requests, would appreciate it if I could be kept in the loop as I didn't expect alycecil would be allowed back on the workshop.

**Comment by alycecil** [comment] 2018-12-09 14:17
I don't understand why you are talking about my copyright material as if its not.

**Comment by inexcode** [comment] 2018-12-09 14:53
Because it's not. We use uncopyrighted versions of your mods, i.e. public domain versions.

**Comment by inexcode** [comment] 2018-12-09 15:01
@alycecil look. I'm not here to fight, but you must understand that I can't betray lots of people who trusted me, like you did. That's the reason why I'm not willing to delete your mods.

**Comment by alycecil** [comment] 2018-12-09 15:02
@inexcode submitted DMCA, how you feel is irreverent. I own this content.

**Comment by inexcode** [comment] 2018-12-09 15:07
Once again: we used public domain versions of your mods. Everything after you added CC-NC-ND was reverted.
If you want to continue conversation like this, please, DM me instead.

**Comment by inexcode** [comment] 2018-12-09 15:13
> your feeling are irrelevant

What about yours, when you did things that lead as here? It would be very kind of you, if you just let us continue your mods and forget about it.

**Comment by inexcode** [comment] 2018-12-09 18:23
Ohh, wait, @alycecil
We didn't make any code changes in this mod yet so we didn't create a derivative work. Just an old version. And CC-NC-ND lets us distribute this!
How about this?
